### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by adminlove520** [uzdz/rooms-inspect-robot#1]
请问如何部署呢？是否支持actions部署

**Comment by uzdz** [comment]
请问有go的经验吗？或者本地有go环境？

如果没有的话提供下运行服务的系统，例如：Mac、Linux、Windows

我来帮你编译可执行文件，本代码用Go语言编写，可以交叉编译各种系统。

其他的使用方案请参考README.md，有疑问可提Issues。
